### ISSUE TITLE
Luka Checklist

### ISSUE THREAD

**Issue by LukaVDB** [hsinaDitaM/Tea_Lounge#2]
- [x] Working tools
- [x] Finish Notes on the algorithm lesson
- [x] Lesson plan for lesson 3.3.1
- [x] Creative idea for lesson
- [ ] Finish Binary Hacks
