### ISSUE TITLE
Mati's Checklist wk1

### ISSUE THREAD

**Issue by hsinaDitaM** [hsinaDitaM/Tea_Lounge#3]
- [x] Check tools
- [x] Finish binary hack
- [x] Add lesson planning
- [x] Watch and take on notes on the college board videos
- [x] Add notes to the lesson planning fast page
- [x] Make fun activities for the teaching part. 
- [x] Finished this checklist
